"""empty message

Revision ID: 6077efb5d25d
Revises: daa4bcb383f5
Create Date: 2022-06-21 23:42:41.841029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6077efb5d25d'
down_revision = 'daa4bcb383f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urlvalues', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urlvalues', 'description')
    # ### end Alembic commands ###
